config/routes.rb
Rails.application.routes.draw do
  get 'attendees/confirm_email'

  get 'attendees/confirm_email?confirm_token=:confirm_token' => 'attendees#confirm_email', as: :confirm_email

  post 'events/register'

  root "hosts#index"
  
  resources :hosts, only: [:index, :show], :path => ''

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
	has_many :registrations

	attr_accessor :event_ids, :host_id
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :host
	has_many :regisrations
	scope :future, -> { where("date_time > ?", DateTime.now.tomorrow).order(date_time: :asc)}

	def register(details)
		eventbrite = Eventbrite.new
		response = eventbrite.register(url, details)
		unless response
			return response
		end
	end
end

app/models/host.rb
class Host < ActiveRecord::Base

	extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :events

	def find_or_create_events
		eventbrite = Eventbrite.new

		fetched_events = eventbrite.get_events(events_url)

		events = []

		fetched_events.each do |event|
			events.push(Event.find_or_create_by(url: event[:url], host_id: id, date_time: event[:date_time], date: event[:date] ))
		end
		events

		fields_hash = {}

		fields_array = eventbrite.get_event_fields(events[-1][:url])
		fields_array.each do |field|
			fields_hash[field] = field.titleize
		end
		update_attributes(fields: fields_hash)
		

	end
end

app/models/registration.rb
class Registration < ActiveRecord::Base
	belongs_to :attendee
	belongs_to :event

	def confirm
		EventWorker.perform_async(attendee.details, event.id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def confirm_email
  	@attendee = Attendee.find_by(confirm_token: params[:confirm_token])
  	@events = []
  	if @attendee.present?
  		@attendee.confirmed = true
  		@attendee.save
  		@attendee.registrations.where(completed: nil).each do |registration|
  			registration.completed = true
  			registration.confirm
  			registration.save
  			@events.push(registration.event)

  		end
  	else
  		render json: {success: false}
  	end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def register
  	@attendee = Attendee.find_or_create_by(email: params[:attendee][:details][:email_address])
  	@attendee.confirm_token = (0...50).map { ('a'..'z').to_a[rand(26)] }.join
  	@attendee.details = params[:attendee][:details]
  	@attendee.save
  	@events = []
  	params[:attendee][:event_ids].each do |id|
  		unless id == ""
  			registration = @attendee.registrations.find_or_create_by(event_id: id)
  			@events.push(registration.event)
  		end
  	end
  	@host = @events.first.host
  	EventMailer.confirm_email(@attendee.id, params[:attendee][:host_id], params[:attendee][:event_ids]).deliver_later
  end
  protected
  	def attendee_params
  		params.require(:attendee).permit(details: {}, event_ids: [])
  	end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  def index
  	@hosts = Host.all
  end

  def show
  	@host = Host.friendly.find(params[:id])

		@events = @host.events.future

		@attendee = Attendee.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/attendees/confirm_email.html.erb
<div class="container">
	<div class="row">
	<h2>Your email has been confirmed!</h2>
	<% if @events.length > 0 %>
	<p>If all goes well with scraping Eventbrite, you will soon be getting emails for the following events:</p>
	<ul>
	<% @events.each do |event| %>
		<li><%= event.date %></li>
	<%end%>
	</ul>
	<% end %>
	</div>
</div>

app/views/events/register.html.erb
<p>Please click on the link in the confirmation email address that is being sent to complete registration to the following events hosted by <%= @host.title %>: </p>
<ul>
<% @events.each do |event| %>
	<li><%= event.date %></li>
<%end%>
</ul>

app/views/hosts/index.html.erb
<div class="container">
	<div class="row">
	<h2>Hosts</h2>
	<% @hosts.each do |host| %>
	    <div class="panel panel-default panel-brand">
	    	<div class="panel-body">
		      <h3><%= host.title %></h3>
		      <h5><a href="<%= host.website %>">Website</a> | <%= host.address %></h5>
		     </div>
		      <div class="panel-footer "><a href="<%= host_path(host) %>" class="">RSVP to Events</a></div>
	    </div>
	 <% end %>
	</div>
</div>

app/views/hosts/show.html.erb
<div class="container">
	<div class="row">
	<h2><%= @host.title %></h2>
	<p>Please use a valid email address, as you will need to confirm your registration via an email sent upon submission of this form.</p>
	<%= simple_form_for @attendee, url: events_register_path do |f| %>

	  <%= f.simple_fields_for :details do |d| %>
	      <% @host.fields.try(:each) do |key, value| %>
	      	<% if f.object.details[key].nil? %>
	         	<%= d.input key, :input_html => {:value => nil }, label: value %>
	         <% else %>
	         	<%= d.input key, :input_html => {:value => f.object.details[key] } %>
	         <% end %>
	      <% end %>
	  <% end %>
	  <%= f.input :host_id, as: :hidden, :input_html => {:value => @host.id } %>
	  <%= f.input :event_ids, collection: @events, label_method: :date, value_method: :id, as: "check_boxes", label: "Upcoming Events" %>

	  <%= f.button :submit, "RSVP to Selected Events" %>
	<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class="container">
	<span><h1><a href="<%= root_path %>">Attend</a></h1>
	<h4>Quickly RSVP to recurring Eventbrite events.</h4>
	</span>
	<nav>
		<ul>
			
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Attend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='//fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

	<%= yield %>

</body>
</html>